UPDATE tpzdb . mob_pools SET sJob = 1 WHERE familyid = 200;
UPDATE tpzdb . mob_pools SET sJob = 1 WHERE familyid = 201;
UPDATE tpzdb . mob_pools SET sJob = 1 WHERE familyid = 202;
UPDATE tpzdb . mob_pools SET sJob = 1 WHERE familyid = 270;
UPDATE tpzdb . mob_pools SET skill_list_id = 1163 WHERE familyid = 942;
UPDATE tpzdb . mob_pools SET skill_list_id = 1164  WHERE familyid = 943;
UPDATE tpzdb . mob_pools SET skill_list_id = 1165 WHERE familyid = 944;
UPDATE tpzdb . mob_pools SET cmbDelay = 120 WHERE familyid = 131;
UPDATE tpzdb . mob_pools SET cmbDelay = 260 WHERE familyid = 203;
UPDATE tpzdb . mob_pools SET cmbDelay = 260 WHERE familyid = 204;
UPDATE tpzdb . mob_pools SET cmbDelay = 260 WHERE familyid = 205;
UPDATE tpzdb . mob_pools SET cmbDelay = 290 WHERE familyid = 251;
UPDATE tpzdb . mob_pools SET cmbSkill = 1 WHERE familyid = 246;
UPDATE tpzdb . mob_pools SET cmbSkill = 1 WHERE familyid = 326;
UPDATE tpzdb . mob_pools SET cmbSkill = 1 WHERE familyid = 923;
UPDATE tpzdb . mob_pools SET cmbDmgMult = 50 WHERE familyid = 246;
UPDATE tpzdb . mob_pools SET cmbDmgMult = 50 WHERE familyid = 326;
UPDATE tpzdb . mob_pools SET cmbDmgMult = 50 WHERE familyid = 923;
UPDATE tpzdb . mob_pools SET mJob = 1 WHERE familyid = 218;
UPDATE tpzdb . mob_pools SET sJob = 1 WHERE familyid = 218;
UPDATE tpzdb . mob_pools SET mJob = 1 WHERE familyid = 219;
UPDATE tpzdb . mob_pools SET sJob = 1 WHERE familyid = 219;
UPDATE tpzdb . mob_pools SET mJob = 1 WHERE familyid = 551;
UPDATE tpzdb . mob_pools SET sJob = 1 WHERE familyid = 551;
UPDATE tpzdb . mob_pools SET namevis = 0 WHERE namevis = 1;
UPDATE tpzdb . mob_pools SET cmbSkill = 1 WHERE familyid = 3 AND mJob = 2;
UPDATE tpzdb . mob_pools SET cmbDelay = 480 WHERE familyid = 3 AND mJob = 2;
UPDATE tpzdb . mob_pools SET cmbDmgMult = 50 WHERE familyid = 3 AND mJob = 2;
UPDATE tpzdb . mob_pools SET cmbSkill = 1 WHERE familyid = 3 AND mJob = 13;
UPDATE tpzdb . mob_pools SET cmbDelay = 360 WHERE familyid = 3 AND mJob = 13;
UPDATE tpzdb . mob_pools SET cmbDmgMult = 50 WHERE familyid = 3 AND mJob = 13;
UPDATE tpzdb . mob_pools SET cmbSkill = 1 WHERE familyid = 176 AND mJob = 13;
UPDATE tpzdb . mob_pools SET cmbDelay = 360 WHERE familyid = 176 AND mJob = 13;
UPDATE tpzdb . mob_pools SET cmbDmgMult = 50 WHERE familyid = 176 AND mJob = 13;

